FROM python:3.10-slim

WORKDIR /app

# Instala dependências do sistema e ferramentas de diagnóstico (curl e netcat)
RUN apt-get update && apt-get install -y \
    libpq-dev \
    gcc \
    curl \
    netcat-openbsd \
    && rm -rf /var/lib/apt/lists/*

# Instala as dependências do Python
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copia o código da API
COPY . .

# Expõe a porta do Flask
EXPOSE 5000

# Comando para iniciar a API
CMD ["python", "api.py"]