version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: onelog_db
    environment:
      POSTGRES_USER: ${DB_USER:-onelog}
      POSTGRES_PASSWORD: ${DB_PASS:-onelog_password}
      POSTGRES_DB: ${DB_NAME:-onelog_db}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    # Banco de dados consome pouco, mas vamos limitar por segurança
    deploy:
      resources:
        limits:
          memory: 256M

  redis:
    image: redis:7-alpine
    container_name: onelog_redis
    volumes:
      - redis_data:/data
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 128M

  api:
    build: 
      context: .
      dockerfile: Dockerfile.api
    container_name: onelog_api
    ports:
      - "5000:5000"
    environment:
      - REDIS_URL=redis://redis:6379/0
      - DB_URL=postgresql://${DB_USER:-onelog}:${DB_PASS:-onelog_password}@db:5432/${DB_NAME:-onelog_db}
      - AD_SERVER_IP=${AD_SERVER_IP}
      - AD_DOMAIN=${AD_DOMAIN}
      - PYTHONUNBUFFERED=1
    depends_on:
      - redis
      - db
    volumes:
      - ./static:/app/static
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 400M

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    container_name: onelog_worker
    shm_size: 2gb
    environment:
      - REDIS_URL=redis://redis:6379/0
      - DB_URL=postgresql://${DB_USER:-onelog}:${DB_PASS:-onelog_password}@db:5432/${DB_NAME:-onelog_db}
      - PYTHONUNBUFFERED=1
    volumes:
      - ./static:/app/static
    depends_on:
      - redis
      - db
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.80'        # Usa no máximo 80% de 1 vCPU
          memory: 800M        # Se o Chrome "vazar" memória e passar de 800MB, o Docker reinicia o container
        reservations:
          memory: 300M        # Reserva o mínimo para o boot do Chrome

volumes:
  postgres_data:
  redis_data: